POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 1,
  "mediaType": "MOVIE",
  "title": "Thương ngày nắng về",
  "description": "test sample",
  "mediaAsset": {
    "id": 1,
    "bannerUrl": "sample.com/banner.png",
    "posterUrl": "sample.com/posterUrl.png",
    "thumbnailUrl": "sample.com/thumbnailUrl.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9001,
      "url": "sample.com/linkPlayHLSIOS01.mp4",
      "platform": "IOS"
    },
    {
      "id": 9002,
      "url": "sample.com/linkPlayAndroidDASH01.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": [
    "Tường Vi",
    "Hoài An",
    "Đào Anh Tuấn",
    "Hứa Minh Đạt",
    "Hùng Phạm"
  ],
  "directors": [
    "Khương Thịnh"
  ],
  "channelId": null,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 2,
  "mediaType": "MOVIE",
  "title": "Chồng cũ, vợ cũ, người yêu cũ",
  "description": "test sample",
  "mediaAsset": {
    "id": 2,
    "bannerUrl": "sample.com/banner02.png",
    "posterUrl": "sample.com/posterUrl02.png",
    "thumbnailUrl": "sample.com/thumbnailUrl02.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9003,
      "url": "sample.com/linkPlayHLSIOS02.mp4",
      "platform": "IOS"
    },
    {
      "id": 9004,
      "url": "sample.com/linkPlayAndroidDASH02.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": [
    "Lã Thanh Huyền",
    "Việt Anh"
  ],
  "directors": [
    "Khương Thịnh"
  ],
  "channelId": null,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 3,
  "mediaType": "MOVIE",
  "title": "Bão ngầm",
  "description": "test sample",
  "mediaAsset": {
    "id": 3,
    "bannerUrl": "sample.com/banner.png",
    "posterUrl": "sample.com/posterUrl.png",
    "thumbnailUrl": "sample.com/thumbnailUrl.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9005,
      "url": "sample.com/linkPlayIOS03.mp4",
      "platform": "IOS"
    },
    {
      "id": 9006,
      "url": "sample.com/linkPlayAndroid03.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": [
    "Cao Thái Hà",
    "NSND Nguyễn Hải",
    "NSND Trần Nhượng"
  ],
  "directors": [
    "Thanh Trúc"
  ],
  "channelId": null,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 4,
  "mediaType": "MOVIE",
  "title": "Trà táo đỏ (Phần 2)",
  "description": "test sample",
  "mediaAsset": {
    "id": 3,
    "bannerUrl": "sample.com/banner.png",
    "posterUrl": "sample.com/posterUrl.png",
    "thumbnailUrl": "sample.com/thumbnailUrl.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9007,
      "url": "sample.com/linkPlayIOS04.mp4",
      "platform": "IOS"
    },
    {
      "id": 9007,
      "url": "sample.com/linkPlayAndroid04.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": [
    "Quý Bình",
    "Hà Trí Quang",
    "Thanh Hiền",
    "Ngân Quỳnh"
  ],
  "directors": [
    "Tuấn Tú"
  ],
  "channelId": null,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 5,
  "mediaType": "MOVIE",
  "title": "Anh có phải đàn ông không?",
  "description": "test sample",
  "mediaAsset": {
    "id": 5,
    "bannerUrl": "sample.com/banner05.png",
    "posterUrl": "sample.com/posterUrl05.png",
    "thumbnailUrl": "sample.com/thumbnailUrl05.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9009,
      "url": "sample.com/linkPlayIOS05.mp4",
      "platform": "IOS"
    },
    {
      "id": 9010,
      "url": "sample.com/linkPlayAndroid05.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": [
    "Nhan Phúc Vinh",
    "Hà Việt Dũng",
    "Thúy An",
    "Quỳnh Kool",
    "Việt Hoa"
  ],
  "directors": [
    "Trọng Lân"
  ],
  "channelId": null,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 6,
  "mediaType": "MOVIE",
  "title": "Lối về miền hoa",
  "description": "test sample",
  "mediaAsset": {
    "id": 6,
    "bannerUrl": "sample.com/banner06.png",
    "posterUrl": "sample.com/posterUrl06.png",
    "thumbnailUrl": "sample.com/thumbnailUrl06.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9011,
      "url": "sample.com/linkPlayIOS06.mp4",
      "platform": "IOS"
    },
    {
      "id": 9012,
      "url": "sample.com/linkPlayAndroid06.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": [
    "Lâm Đức Anh",
    "Mạnh Quân",
    "Anh Đào"
  ],
  "directors": [
    "Khương Thịnh"
  ],
  "channelId": null,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 11,
  "mediaType": "PROGRAM",
  "title": "Chào buổi sáng",
  "description": "test sample",
  "mediaAsset": {
    "id": 11,
    "bannerUrl": "sample.com/banner11.png",
    "posterUrl": "sample.com/posterUrl11.png",
    "thumbnailUrl": "sample.com/thumbnailUrl11.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9021,
      "url": "sample.com/linkPlayIOS11.mp4",
      "platform": "IOS"
    },
    {
      "id": 9022,
      "url": "sample.com/linkPlayAndroid11.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": null,
  "directors": null,
  "channelId": 222333011,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 12,
  "mediaType": "PROGRAM",
  "title": "Chuyển động 24h",
  "description": "test sample",
  "mediaAsset": {
    "id": 12,
    "bannerUrl": "sample.com/banner12.png",
    "posterUrl": "sample.com/posterUrl12.png",
    "thumbnailUrl": "sample.com/thumbnailUrl12.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9023,
      "url": "sample.com/linkPlayIOS12.mp4",
      "platform": "IOS"
    },
    {
      "id": 9024,
      "url": "sample.com/linkPlayAndroid12.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": null,
  "directors": null,
  "channelId": 222333012,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 13,
  "mediaType": "PROGRAM",
  "title": "Con đường âm nhạc",
  "description": "test sample",
  "mediaAsset": {
    "id": 13,
    "bannerUrl": "sample.com/banner13.png",
    "posterUrl": "sample.com/posterUrl13.png",
    "thumbnailUrl": "sample.com/thumbnailUrl13.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9025,
      "url": "sample.com/linkPlayIOS13.mp4",
      "platform": "IOS"
    },
    {
      "id": 9026,
      "url": "sample.com/linkPlayAndroid13.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": null,
  "directors": null,
  "channelId": 222333013,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 14,
  "mediaType": "PROGRAM",
  "title": "Người đương thời",
  "description": "test sample",
  "mediaAsset": {
    "id": 14,
    "bannerUrl": "sample.com/banner14.png",
    "posterUrl": "sample.com/posterUrl14.png",
    "thumbnailUrl": "sample.com/thumbnailUrl14.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9027,
      "url": "sample.com/linkPlayIOS14.mp4",
      "platform": "IOS"
    },
    {
      "id": 9028,
      "url": "sample.com/linkPlayAndroid14.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": null,
  "directors": null,
  "channelId": 222333014,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 15,
  "mediaType": "PROGRAM",
  "title": "Bạn của nhà nông",
  "description": "test sample",
  "mediaAsset": {
    "id": 15,
    "bannerUrl": "sample.com/banner15.png",
    "posterUrl": "sample.com/posterUrl15.png",
    "thumbnailUrl": "sample.com/thumbnailUrl15.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9029,
      "url": "sample.com/linkPlayIOS15.mp4",
      "platform": "IOS"
    },
    {
      "id": 9030,
      "url": "sample.com/linkPlayAndroid15.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": null,
  "directors": null,
  "channelId": 222333015,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 16,
  "mediaType": "PROGRAM",
  "title": "Công nghệ 360",
  "description": "test sample",
  "mediaAsset": {
    "id": 16,
    "bannerUrl": "sample.com/banner16.png",
    "posterUrl": "sample.com/posterUrl16.png",
    "thumbnailUrl": "sample.com/thumbnailUrl16.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9031,
      "url": "sample.com/linkPlayIOS16.mp4",
      "platform": "IOS"
    },
    {
      "id": 9032,
      "url": "sample.com/linkPlayAndroid16.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": null,
  "directors": null,
  "channelId": 222333016,
  "player": null
}

###
POST http://localhost:8080/api/consumer
Content-Type: application/json

{
  "id": 17,
  "mediaType": "PROGRAM",
  "title": "Hành trình khám phá",
  "description": "test sample",
  "mediaAsset": {
    "id": 17,
    "bannerUrl": "sample.com/banner17.png",
    "posterUrl": "sample.com/posterUrl17.png",
    "thumbnailUrl": "sample.com/thumbnailUrl17.png"
  },
  "startTime": "2022-08-20T01:00:00.001",
  "expiredTime": "2022-08-23T01:00:00.001",
  "linkPlay": [
    {
      "id": 9033,
      "url": "sample.com/linkPlayIOS17.mp4",
      "platform": "IOS"
    },
    {
      "id": 9034,
      "url": "sample.com/linkPlayAndroid17.mp4",
      "platform": "ANDROID"
    }
  ],
  "actors": null,
  "directors": null,
  "channelId": 222333017,
  "player": null
}

